### PR TITLE
Create proposal-of-move-to-discord

### PR DESCRIPTION
**Pull request by josh-levinson**

### CODE REVIEW

**Comment by Quinncuatro** [comment]
Worth noting there was a collection of opinions here: https://github.com/newhavenio/playbooks/issues/1

For what it's worth, I think Discord is a lot better at serving this kind of group. They provide better moderation tools, free voice hangouts (which Alex Trost points out is a great tool for building community), and it helps us meet people where they are.

Almost all of my hobby groups are on Discord at this point. I keep Slack around _just_ for IO and a separate DevOps group. If we want folks to be involved in New Haven IO outside of the regular 9-5 I think it's important to use a tool that people will be using outside of work hours... and more and more it's seeming like Slack is a work tool on work machines.

**Comment by Quinncuatro** [comment]
From Tom Reznick:

> Can we take a step back and frame the problem we're trying to solve here? Moving to discord may be a good move however I want to frame the conversation around the actual issue?

Personally, I think the problem is that member activity is dropping off a cliff. 

The group in Slack has whittled down to a handful of core members while I'm seeing all my other tech based groups thrive on Discord. I think that's in no small part due to the fact the it's an app people are already used to using in their free time and provides better tools for community building than just text threads.

Since we're already hemorrhaging active members, doesn't really seem like a risk to make the jump. Especially if we communicate the change well and set up some Slackbot responses to point stragglers (with clear instructions) over to the new Discord.

**Comment by josh-levinson** [comment]
We will also need to update the website if we were to make this move. Get
some equivalent to "click for invitation" but for discord.

**Comment by Quinncuatro** [comment]
Frankly, Discord makes that "Click for invitation" bit way easier than Slack does.

**Comment by Christopher-Hayes** [comment]
I'm a huge fan of Slack; however, even Slack admits that they don't build it with communities in mind. Discord is just better formatted for communities and it doesn't seem like Slack is changing course anytime soon. I'll always like Slack better, but this would be the right move for nhv.io. And as mentioned it's much easier to invite people to Discord servers.

**Comment by Quinncuatro** [comment]
Another benefit is that members are automatically subbed to all the available channels in Discord. Folks wouldn't need to go spelunking to find #space, #ruby, or #talk-pay.

**Comment by mzagaja** [comment]
I think it is important to separate the concerns of what Discord can inherently solve versus what are larger organizational challenges. If the issue is "member activity is falling off a cliff" is this really an issue with Slack, or is it that the lack of IRL events to drive awareness and membership into the Slack? IMHO we have just reached a point where the macro trend is folks are deciding to engage less in virtual communities overall in favor of real world events after two plus years of COVID. This is compounded by the summer lull of vacations. We see this at Code for Boston every year. In August we ask ourselves "is this thing dead" and then September/October it lights back up.

I think there are some other good reasons to move to Discord enumerated above. Ultimately I am indifferent. I will go where the people are.

**Comment by danbernier** [comment]
I agree with @mzagaja - there are doubtless lots of reasons why folks are participating less, and moving to discord won't inherently solve them.

The points raised in favor of discord (it's better-suited for communities, it's where people are, NHv.io is "the only" group on slack) aren't especially compelling in isolation, but in aggregate, they convince me. At some point in the coming 12 months, I think NHv.io should move to discord, especially while the community has energy to move.

The biggest risk is leaving occasionally-active folks behind. Let's set up slackbot to forward them on to discord (it's a shame iobot had to die when it did, that could've been fun), and let's maybe think about moving in October, after summer's over but before the holidays?

**Comment by Quinncuatro** [comment]
I feel like early/mid October is a good target. Gives us time to get everything set up.

The Discord bit shouldn't take too long but we need to get the communication and Slackbot auto-responses in order.

**Comment by Quinncuatro** [comment]
Set up a test server on Discord to play with settings and figure out how we'd like an IO server set up. This is a quick write up on moderation adjacent settings that should make running the community easier.

Roles:
- @Admin: full privileges
- @Everyone: “Regular” participation privileges, minus ability to create new channels.
- Also allows us to create more roles so we could have tiers of moderators without the current method 
of either being a member or an admin.

Music:
- Added a Hydra (https://hydra.bot/) bot to allow us to play music in the #Music voice channel.

Invite Links:
- Way easier to create an “Invite” button for the website, since we can generate links on the fly.

Rules Screening:
- Set up a rules screen, so that when members join they have to see and agree to a set of rules pulled 
from our Code of Conduct in order to join the server.
- It also includes an email verification and a link to our full Code of Conduct.

Safety Setup:
- Verification Level is set to medium, meaning users must be registered on Discord longer than 5 
minutes in order to send messages – in a hope to prevent drive by scammers.
- Explicit Media Content Filter is set to automatically scan media content from all members for explicit
content.
- Moderators are required to have 2FA set up in order to prevent compromised accounts from trashing 
the server.

AutoMod (Beta):
- Commonly Flagged Words is toggled to on. It watches for severe profanity, insults & slurs, and sexual
content. It’ll block those messages and send an alert to our private #organizers channel so we can 
review it.
- There’s also the ability to set up custom keyword rules that follow the same block & alert protocol for
commonly flagged words.

Bans:
- Bans are at an account and IP level. Since IP level bans can be beat using a proxy, we could require all
users have a verified phone number on their Discord account in order to access the server, but that 
seems a bit extreme for our group.

Server Insights:
- Analytics are built in. The test server hasn’t been used long enough to see anything useful yet, but we 
should be able to see things like how active different channels are, where users are coming from, etc...

Welcome Screen:
- Still need to set this up, but it’s a screen all new members will see, and can act as a map of sorts for 
how to get involved in different channels on the server.

**Comment by nrawling** [comment]
Slack isn't serving us well anymore, so we'll switch to Discord. Seems fine. I don't think it's going to fix any real problems, though (e.g. the membership attrition, general malaise, etc.). However, I think reducing the number of Electron clients on @Quinncuatro's laptop is itself a worthwhile cause, however. The support for roles and bots is definitely better in Discord. 

Policing Discord servers also seems to be a much worse problem than policing Slack. I'm not sure why that it, but it seems like every 9yo has 200 alts they use to harass other Discord servers. Discord is also pretty spammy, constantly prompting you to boost. 

I hate get automatically added to every new channel.

**Comment by Jawn78** [comment]
I am personally involved in far more technology related discords than I am slacks. Discord does have some really great moderation bots and tools and a ton of people making more. 

One thing I have noticed to @nrawling  point is that if the server is completely public it can get crazy with trolls and children acting a fool. On some of the Recruiting/HR/Job discords I am a part of they have everyone go through somewhat of a vetting process up front to request a tag/role. To do that they have to fill out a couple of questions that then get approved.

**Comment by caseywatts** [comment]
I wrote up a “Discord Onboarding” doc that might help here!

Several communities I’m in use Discord a lot, so I articulated a bunch of the big gotchas that people experience when learning how to Discord.

A lot of the “I just don’t like the UI” impressions are covered/articulated here I think (and if you can think of more bumps please let me know, I’d love to update this article even more)

https://www.happyandeffective.com/blog/discord-onboarding

**Comment by caseywatts** [comment]
Today I finally figured out how to set up "reaction roles" using a bot!! carl.gg bot

Reaction roles are like when you click on an emoji to get auto-added to a role to get auto-added to some channels

And then after I struggled through it all, I realized there's probably a YouTube video about it -- and there is!!

This is the shortest and most up-to-date video I found on Carl Bot reaction roles: https://www.youtube.com/watch?v=G5NiSkQlW9Y&t=0s

In case anyone else wants to set up a server with reaction roles, this is the most straightforward way I've seen or heard of! :D

**Comment by kljensen** [comment]
Late to the discussion. Happy to move to Discord. I don't often contribute on Slack and will likely be the same on Discord ;(

**Pull request closed without merging**
